pipeline{
     agent any
     stages{
         stage('SCM Checkout'){
             steps{
                 git 'https://github.com/oayoade/ansible-config-mgt.git'
             }
         }
         stage('Execute Ansible'){
             steps{
                 ansiblePlaybook credentialsId: 'd29c4443-0f41-4a5b-924b-6d0c9bb49b40', disableHostKeyChecking: true, installation: 'Ansible', inventory: 'dev.yml', playbook: 'site.yml'
             }
         }
     }
}

